bitbot.ledRainbow()
bitbot.select_model(BBModel.Classic)
bitbot.goms(BBDirection.Forward, 60, 1000)
bitbot.rotatems(BBRobotDirection.Left, 60, 1000)
bitbot.rotatems(BBRobotDirection.Right, 60, 1000)
bitbot.goms(BBDirection.Forward, 60, 2000)
